### ISSUE TITLE
`ASGARD_NUM_QUADRATURE=3` Crashes

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#653]
**Describe the bug**
Using 3 quadrature points currently crashes ASGarD in the Riemann 1x3v problem.  4+ quadrature points works fine.

**To Reproduce**
1. Build with `cmake -DASGARD_RECOMMENDED_DEFAULTS=ON -DASGARD_IO_HIGHFIVE=ON -DASGARD_USE_CUDA=ON -DASGARD_NUM_QUADRATURE=3`
2.  Run with `./asgard -p riemann_1x3v -d 3 -l "7 3 3 3" --mixed_grid_group 1 -x -t 2.3419e-4 -n 10 --wave_freq 1 --tol 1.0e-8 --kron-mode sparse --inner_it 50`

**Additional context**
Here's the debug output:
```
asgard: /home/7r9/develop/asgard/src/batch.cpp:319: asgard::batch_chain<P, resrc, method>::batch_chain(const std::vector<asgard::fk::matrix<P, asgard::mem_type::const_view, resrc> >&, const asgard::fk::vector<P, asgard::mem_type::const_view, resrc>&, std::array<asgard::fk::vector<P, asgard::mem_type::view, resrc>, 2>&, asgard::fk::vector<P, asgard::mem_type::view, resrc>&) [with asgard::chain_method m_ = asgard::chain_method::realspace; <template-parameter-2-2> = void; P = double; asgard::resource resrc = asgard::resource::host; asgard::chain_method method = asgard::chain_method::realspace]: Assertion `workspace[0].size() >= workspace_len' failed.
```

**Comment by mkstoyanov** [comment]
Can't reproduce!

Are you running this on Andre?

**Comment by stefan-schnake** [comment]
> Can't reproduce!
> 
> Are you running this on Andre?

Yes.  Reboot did not fix the issue.

**Comment by quantumsteve** [comment]
```
asgard: /home/svh/Documents/asgard/src/batch.cpp:319: asgard::batch_chain<P, resrc, method>::batch_chain(const std::vector<asgard::fk::matrix<P, asgard::mem_type::const_view, resrc> >&, const asgard::fk::vector<P, asgard::mem_type::const_view, resrc>&, std::array<asgard::fk::vector<P, asgard::mem_type::view, resrc>, 2>&, asgard::fk::vector<P, asgard::mem_type::view, resrc>&) [with asgard::chain_method m_ = asgard::chain_method::realspace; <template-parameter-2-2> = void; P = double; asgard::resource resrc = asgard::resource::host; asgard::chain_method method = asgard::chain_method::realspace]: Assertion `workspace[0].size() >= workspace_len' failed.

Thread 1 "asgard" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737220233600) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737220233600) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737220233600) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737220233600, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fffef042476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fffef0287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fffef02871b in __assert_fail_base (fmt=0x7fffef1dd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x555555905e98 "workspace[0].size() >= workspace_len", 
    file=0x555555905258 "/home/svh/Documents/asgard/src/batch.cpp", line=319, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007fffef039e96 in __GI___assert_fail (assertion=0x555555905e98 "workspace[0].size() >= workspace_len", file=0x555555905258 "/home/svh/Documents/asgard/src/batch.cpp", line=319, 
    function=0x555555905bc8 "asgard::batch_chain<P, resrc, method>::batch_chain(const std::vector<asgard::fk::matrix<P, asgard::mem_type::const_view, resrc> >&, const asgard::fk::vector<P, asgard::mem_type::const_view, resrc>&, s"...) at ./assert/assert.c:101
#7  0x00005555558c159a in asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0>::batch_chain<(asgard::chain_method)0, void> (this=0x555571d3f4c0, 
    matrices=std::vector of length 1, capacity 1 = {...}, x=..., workspace=..., final_output=...) at /home/svh/Documents/asgard/src/batch.cpp:319
#8  0x00005555556e3d6b in __gnu_cxx::new_allocator<asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0> >::construct<asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0>, std::vector<asgard::fk::matrix<double, (asgard::mem_type)2, (asgard::resource)0>, std::allocator<asgard::fk::matrix<double, (asgard::mem_type)2, (asgard::resource)0> > >&, asgard::fk::vector<double, (asgard::mem_type)2, (asgard::resource)0> const&, std::array<asgard::fk::vector<double, (asgard::mem_type)1, (asgard::resource)0>, 2ul>&, asgard::fk::vector<double, (asgard::mem_type)1, (asgard::resource)0>&> (this=0x7fffffffc960, __p=0x555571d3f4c0) at /usr/include/c++/11/ext/new_allocator.h:162
#9  0x00005555556e31c5 in std::allocator_traits<std::allocator<asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0> > >::construct<asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0>, std::vector<asgard::fk::matrix<double, (asgard::mem_type)2, (asgard::resource)0>, std::allocator<asgard::fk::matrix<double, (asgard::mem_type)2, (asgard::resource)0> > >&, asgard::fk::vector<double, (asgard::mem_type)2, (asgard::resource)0> const&, std::array<asgard::fk::vector<double, (asgard::mem_type)1, (asgard::resource)0>, 2ul>&, asgard::fk::vector<double, (asgard::mem_type)1, (asgard::resource)0>&> (__a=..., __p=0x555571d3f4c0) at /usr/include/c++/11/bits/alloc_traits.h:516
#10 0x00005555556e32fd in std::vector<asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0>, std::allocator<asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0> > >::_M_realloc_insert<std::vector<asgard::fk::matrix<double, (asgard::mem_type)2, (asgard::resource)0>, std::allocator<asgard::fk::matrix<double, (asgard::mem_type)2, (asgard::resource)0> > >&, asgard::fk::vector<double, (asgard::mem_type)2, (asgard::resource)0> const&, std::array<asgard::fk::vector<double, (asgard::mem_type)1, (asgard::resource)0>, 2ul>&, asgard::fk::vector<double, (asgard::mem_type)1, (asgard::resource)0>&> (this=0x7fffffffc960, __position=non-dereferenceable iterator for std::vector) at /usr/include/c++/11/bits/vector.tcc:449
#11 0x00005555556e23e8 in std::vector<asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0>, std::allocator<asgard::batch_chain<double, (asgard::resource)0, (asgard::chain_method)0> > >::emplace_back<std::vector<asgard::fk::matrix<double, (asgard::mem_type)2, (asgard::resource)0>, std::allocator<asgard::fk::matrix<double, (asgard::mem_type)2, (asgard::resource)0> > >&, asgard::fk::vector<double, (asgard::mem_type)2, (asgard::resource)0> const&, std::array<asgard::fk::vector<double, (asgard::mem_type)1, (asgard::resource)0>, 2ul>&, asgard::fk::vector<double, (asgard::mem_type)1, (asgard::resource)0>&> (this=0x7fffffffc960) at /usr/include/c++/11/bits/vector.tcc:121
#12 0x00005555556e07c9 in asgard::wavelet_to_realspace<double> (dims=std::vector of length 1, capacity 1 = {...}, wave_space=..., table=..., transformer=..., workspace=..., 
    real_space=..., quad_mode=asgard::quadrature_mode::use_fixed) at /home/svh/Documents/asgard/src/transformations.cpp:265
#13 0x00005555556e0417 in asgard::wavelet_to_realspace<double> (pde=..., wave_space=..., table=..., transformer=..., workspace=..., real_space=..., 
    quad_mode=asgard::quadrature_mode::use_fixed) at /home/svh/Documents/asgard/src/transformations.cpp:217
#14 0x0000555555688c88 in asgard::moment<double>::create_realspace_moment (this=0x555555dbbb50, pde_1d=..., wave=..., table=..., transformer=..., workspace=...)
    at /home/svh/Documents/asgard/src/moment.cpp:243
#15 0x00005555555ce3b8 in asgard::generate_initial_moments<double> (pde=..., program_opts=..., adaptive_grid=..., transformer=..., initial_condition=...)
    at /home/svh/Documents/asgard/src/io.hpp:134
#16 0x000055555556200e in main (argc=22, argv=0x7fffffffd438) at /home/svh/Documents/asgard/src/main.cpp:234
```

**Comment by mkstoyanov** [comment]
The error is in the batch module, we are no longer using it. See #761
