### ISSUE TITLE
Overflow Error

### ISSUE THREAD

**Issue by stefan-schnake** [project-asgard/asgard#654]
**Describe the bug**
Code crashes when trying to run larger problem.  This does not happen on Cole's branch.  I suspect this is because we're getting close to the 32 bit integer limit.  

**To Reproduce**
1. Run on current develop
2. `./asgard -p riemann_1x3v -d 3 -l "7 6 6 6" --mixed_grid_group 1 -x -t 2.3419e-4 -n 4 --wave_freq 1 --tol 1.0e-8 --kron-mode sparse --inner_it 50 -m 7'

**System:**
 - andremarie

**Additional context**
Debug output: 
```
asgard: /home/7r9/develop/asgard/src/asgard_vector.hpp:513: asgard::fk::vector<P, mem, resrc>::vector(int) [with asgard::mem_type m_ = asgard::mem_type::owner; <template-parameter-2-2> = void; P = double; asgard::mem_type mem = asgard::mem_type::owner; asgard::resource resrc = asgard::resource::host]: Assertion `size >= 0' failed.
```

**Comment by quantumsteve** [comment]
I had to enable HDF5 output to get a crash
```
--- begin time loop staging ---
asgard: /home/svh/Documents/asgard/src/asgard_vector.hpp:513: asgard::fk::vector<P, mem, resrc>::vector(int) [with asgard::mem_type m_ = asgard::mem_type::owner; <template-parameter-2-2> = void; P = double; asgard::mem_type mem = asgard::mem_type::owner; asgard::resource resrc = asgard::resource::host]: Assertion `size >= 0' failed.

Thread 1 "asgard" received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737220233600) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737220233600) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737220233600) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737220233600, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fffef042476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fffef0287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fffef02871b in __assert_fail_base (fmt=0x7fffef1dd130 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555558cdfb9 "size >= 0", 
    file=0x5555558cdf88 "/home/svh/Documents/asgard/src/asgard_vector.hpp", line=513, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007fffef039e96 in __GI___assert_fail (assertion=0x5555558cdfb9 "size >= 0", file=0x5555558cdf88 "/home/svh/Documents/asgard/src/asgard_vector.hpp", line=513, 
    function=0x5555558cde90 "asgard::fk::vector<P, mem, resrc>::vector(int) [with asgard::mem_type m_ = asgard::mem_type::owner; <template-parameter-2-2> = void; P = double; asgard::mem_type mem = asgard::mem_type::owner; asgard:"...) at ./assert/assert.c:101
#7  0x00005555555cd32f in asgard::fk::vector<double, (asgard::mem_type)0, (asgard::resource)0>::vector<(asgard::mem_type)0, void> (this=0x7fffffffce90, size=-1577058304)
    at /home/svh/Documents/asgard/src/asgard_vector.hpp:513
#8  0x0000555555561d5f in main (argc=24, argv=0x7fffffffd418) at /home/svh/Documents/asgard/src/main.cpp:148
```
