### ISSUE TITLE
two_stream throws exception with  ASGARD_USE_MATLAB=ON

### ISSUE THREAD

**Issue by quantumsteve** [project-asgard/asgard#675]
**Describe the bug**

```
No analytic solution found.
Index in position 1 exceeds array bounds. Index must not exceed 192.

Error in plot_fval (line 46)
    f_slice = f_nD(sy,:);

terminate called after throwing an instance of 'matlab::execution::MATLABExecutionException'
  what():  Index in position 1 exceeds array bounds. Index must not exceed 192.
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "asgard" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffefa85859 in __GI_abort () at abort.c:79
#2  0x00007fffefe6fee6 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fffefe81f8c in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fffefe81ff7 in std::terminate() () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fffefe81f7e in std::rethrow_exception(std::__exception_ptr::exception_ptr) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x000055555577313a in std::__basic_future<std::vector<matlab::data::Array, std::allocator<matlab::data::Array> > >::_M_get_result (this=0x7fffffffc800) at /usr/include/c++/11/future:721
#7  0x000055555576e311 in std::future<std::vector<matlab::data::Array, std::allocator<matlab::data::Array> > >::get (this=0x7fffffffc800) at /usr/include/c++/11/future:805
#8  0x000055555576af62 in matlab::execution::FutureResult<std::vector<matlab::data::Array, std::allocator<matlab::data::Array> > >::get (this=0x7fffffffc7f0)
    at /opt/MATLAB/R2023b/extern/include/MatlabExecutionInterface/detail/value_future_impl.hpp:66
#9  0x0000555555758e57 in matlab::execution::ExecutionInterface::feval (this=0x7fff903705b0, function=u"plot_fval", nlhs=0, args=std::vector of length 6, capacity 8 = {...}, 
    output=std::shared_ptr<std::basic_streambuf<char16_t, std::char_traits<char16_t> >> (empty) = {...}, error=std::shared_ptr<std::basic_streambuf<char16_t, std::char_traits<char16_t> >> (empty) = {...})
    at /opt/MATLAB/R2023b/extern/include/MatlabEngine/detail/engine_execution_interface_impl.hpp:194
#10 0x0000555555758f59 in matlab::execution::ExecutionInterface::feval (this=0x7fff903705b0, function="plot_fval", nlhs=0, args=std::vector of length 6, capacity 8 = {...}, 
    output=std::shared_ptr<std::basic_streambuf<char16_t, std::char_traits<char16_t> >> (empty) = {...}, error=std::shared_ptr<std::basic_streambuf<char16_t, std::char_traits<char16_t> >> (empty) = {...})
    at /opt/MATLAB/R2023b/extern/include/MatlabEngine/detail/engine_execution_interface_impl.hpp:202
#11 0x0000555555751a39 in asgard::ml::matlab_plot::call (this=0x555555cca060 <asgard::ml::matlab_plot::get_instance()::instance>, func="plot_fval") at /home/svh/Documents/asgard/src/matlab_plot.cpp:145
#12 0x000055555575cc64 in asgard::ml::matlab_plot::plot_fval<double> (this=0x555555cca060 <asgard::ml::matlab_plot::get_instance()::instance>, dims=std::vector of length 2, capacity 2 = {...}, table=..., 
    f_val=..., analytic_soln=...) at /home/svh/Documents/asgard/src/matlab_plot.cpp:444
#13 0x000055555575c968 in asgard::ml::matlab_plot::plot_fval<double> (this=0x555555cca060 <asgard::ml::matlab_plot::get_instance()::instance>, pde=..., table=..., f_val=..., analytic_soln=...)
    at /home/svh/Documents/asgard/src/matlab_plot.cpp:418
#14 0x000055555556a85f in main (argc=21, argv=0x7fffffffd278) at /home/svh/Documents/asgard/src/main.cpp:364
```

**To Reproduce**
1. git commit hash being built
e2b61dc34191fe7dff487b6d7f53c92ee1c358af
2. cmake command
cmake -DASGARD_USE_MATLAB=ON
3. full program/test invocation command
 ./asgard -p two_stream -d 3 -x -t 0.0023438 -l "7 7" -n 1000 --plot_freq 100 --kron-mode sparse -m 7 --adapt --thresh 1e-4

4. additional steps 

**Expected behavior**

**System:**
 - system name [e.g. fusiont5, summit]
 - modules loaded [e.g. output of `module list`]
 - other systems where this is reproducible [e.g. "my laptop", "none"]

**Additional context**

**Comment by quantumsteve** [comment]
Seems be related to adaptivity

**Comment by mkstoyanov** [comment]
matlab plotting is no longer supported
